# Generated by Django 3.1.4 on 2021-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
